### ISSUE TITLE
Visualization package on ROS

### ISSUE THREAD

**Issue by TheProjectsGuy** [Atom-Robotica/6r_ros#5]
**Task list**
- Create an RViZ configuration that has a RobotModel
- Make the XACRO file
    - Keep it as versatile as possible (several iterations)
- Create a launch file with the robot model as a parameter (.xacro or anything, versatility is important)

## Debug stage
- Test if everything works with custom XACRO files
- Push to GitHub
- Test on a remote system
- Merge pull request

**Assigned to**: @TheProjectsGuy 
**Branch**: `viz-avneesh`

**Comment by TheProjectsGuy** [comment]
Created package with barebones RViZ file and simple URDF file. The following is needed:
- [x] Create a launch file for single command launch
- [x] Create a XACRO file for taking file names as parameters (versatility)
- [x] Test with `.dae` files (collada files from CAD Software)
- [x] Testing the launch in every stage

**Comment by TheProjectsGuy** [comment]
Need to 
- [x] Improve the launch file to have XACRO and URDF compatibility through grouping (if-unless commands)

**Comment by TheProjectsGuy** [comment]
Need to 
- [x] Improve the launch file to have XACRO and URDF compatibility through grouping (if-unless commands)
- [x] XACRO file (with versatility)
- [ ] Whatever's [here](https://github.com/Atom-Robotica/6r_ros/issues/5#issuecomment-538499556)

**Comment by TheProjectsGuy** [comment]
Issue solved, please refer commit `8a509d80296cd58e0933289e5ce2fdef005cdbf7` for result of this commit
